cms/apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView, name="login"),
    path('register/', UserSignupView, name="register"),
    path('logout/', LogoutView, name="logout"),
    path('checkLogin/', isUserLoggedIn, name="check-login"),
    path("forgot-password/", PasswordResetView, name="password_reset"),
    path("forgot-password/validate/<uidb64>/<token>/", PasswordResetTokenValidateView, name="password_reset_confirm"),
    path("register/activate/<uidb64>/<token>/", ActivateAccountTokenValidateView, name="activate-account"),
    path("register/resend-activation/", ResendAccountActivationView, name="resend-account-activation"),
    path('get/users/autocomplete', AutocompleteUsersListView, name="get-autocomplete-users-list"),
]

cms/apps/dashboard/urls.py
from django.urls import path, include
from apps.accounts.views import EnableUser, RemoveUser, SuspendUser, ActivateUser

from . import views as v

app_name = "dashboard"

urlpatterns = [
    path("users/browse/", v.BrowseUsersView, name="list-users"),
    path("profile/", v.UserEditView, name="profile"),
    path("settings/", v.ManageSiteView, name="site-management"),
    path("settings/users/manage/edit/<int:userid>/", v.UserEditView, name="edit-user"),
    path("settings/users/manage/suspend/<int:userid>/", SuspendUser, name="suspend-user"),
    path("settings/users/manage/enable/<int:userid>/", EnableUser, name="enable-user"),
    path("settings/users/manage/remove/<int:userid>/", RemoveUser, name="remove-user"),
    path("settings/users/manage/activate/<int:userid>/", ActivateUser, name="activate-user"),
    path("od/", include("apps.odmanager.urls", namespace="od")),
    path("", v.IndexView, name="home"),
]

cms/cms/urls.py
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    path("c/", include('apps.club.urls', namespace="club")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'
handler400 = 'apps.core.views.bad_request'

cms/apps/dashboard/models.py
from django.db import models

# Create your models here.

cms/apps/dashboard/forms.py
from crispy_forms.bootstrap import InlineRadios
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout, Submit
from django import forms
from django.contrib.auth.forms import AdminPasswordChangeForm
from rolepermissions.checkers import has_permission
from django.core.exceptions import ValidationError
from apps.accounts.models import User
from apps.core.constants import permissions as p
from apps.accounts.roles import Subscriber, Admin
from apps.core.models import Departments, DepartmentBranches
import datetime
class UserForm(forms.ModelForm):

    gender = forms.ChoiceField(
        choices=User.gender_choices,
        widget = forms.RadioSelect
    )

    mobile = forms.CharField(
        label = "Mobile Number"
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'gender', 'avatar', 'mobile', 'date_of_birth', 'enrollment_no', 'registration_year', 'department', 'branch', 'section', 'batch']

    def __init__(self, user, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "container"
        self.helper.label_class = "font-weight-bold"
        # edit_sensitive_fields = True if has_permission(user, p.EDIT_USERS) else False
        edit_sensitive_fields = False
        emailField = Field('email', wrapper_class="col-12 col-md-6")

        if not edit_sensitive_fields:
            emailField = Field('email', readonly=edit_sensitive_fields, wrapper_class="col-12 col-md-6")
            
        self.helper.layout = Layout(
            Div(
                Field('first_name', wrapper_class='col-12 col-md-6'),
                Field('last_name', wrapper_class='col-12 col-md-6'),
                css_class="row"
            ),
            Div(
                emailField,
                Field('mobile', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            Div(
                InlineRadios('gender', wrapper_class="col-12 col-md-6"),
                Field('date_of_birth', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            'avatar',
            Div(
                Field('enrollment_no', wrapper_class="col-12 col-md-6"),
                Field('registration_year', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            Div(
                Field('department', wrapper_class="col-12 col-md-3"),
                Field('branch', wrapper_class="col-12 col-md-3"),
                Field('section', wrapper_class="col-6 col-md-3"),
                Field('batch', wrapper_class="col-6 col-md-3", read_only=edit_sensitive_fields),
                css_class="row"
            ),
        )
        self.helper.add_input(Submit('user-submit', 'Save'))

    def clean_branch(self):
        valid_branches = DepartmentBranches.objects.filter(department = self.cleaned_data['department'])

        if self.cleaned_data['branch'] not in valid_branches:
            raise ValidationError("Invalid Branch for selected department")
        return self.cleaned_data['branch']

    def clean_registration_year(self):
        try:
            year = int(self.cleaned_data['registration_year'])
        except ValueError:
            raise ValidationError("Please enter a valid year!")
        
        if year < 2005 or year > datetime.datetime.now().year:
            raise ValidationError("Value must be greater than 2002 and less than current year!")
        
        return self.cleaned_data['registration_year']

    def clean_section(self):
        try:
            section = int(self.cleaned_data['section'])
        except ValueError:
            raise ValidationError("Please enter a valid section!")
        
        if section < 1 or section > 99:
            raise ValidationError("Please enter a valid section!")

        return self.cleaned_data['section']
    
    def clean_batch(self):
        if len(self.cleaned_data['batch']) > 1:
            raise ValidationError('Enter a valid batch!')
        
        return self.cleaned_data['batch']
    
    def clean_mobile(self):
        if len(self.cleaned_data['mobile']) > 10:
            raise ValidationError('Enter a valid mobile number!')
        for digit in self.cleaned_data['mobile']:
            try:
                int(digit)
            except ValueError as e:
                raise ValidationError("Enter a valid mobile number")
        
        return self.cleaned_data['mobile']

class PasswordChangeForm(AdminPasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.pop("autofocus", None)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"
        
        self.helper.add_input(Submit('password-change', 'Change Password'))

class RolesForm(forms.Form):

    roles = forms.MultipleChoiceField(
        choices = (
            (Subscriber.display_name, Subscriber.title),
            (Admin.display_name, Admin.title)
        )
    )

    def __init__(self, *args, **kwargs):
        super(RolesForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"

        self.helper.add_input(Submit('change-role', 'Save Role(s)'))

class OptionsForm(forms.Form):

    site_title = forms.CharField(label = "Site Title", required=False)
    site_description = forms.CharField(label = "Site Description",required = False)
    support_email = forms.EmailField(label = "Support Email", required=False)
    site_url = forms.URLField(label = "Site URL", required=True)
    smtp_server = forms.CharField(label = "SMTP Server")
    smtp_user = forms.CharField(label = "SMPT User")
    smtp_pass = forms.CharField(label = "SMTP Password")
    smtp_port = forms.CharField(label = "SMTP Port")
    send_mails_as = forms.EmailField(label = "Send Email As")

    def __init__(self, *args, **kwargs):
        super(OptionsForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"
        
        self.helper.layout = Layout(
            Div(
                'site_title',
                'site_url',
                'site_description',
                'support_email',
                css_class="card my-3 my-md-5 p-3"
            ),
            Div(
                'smtp_server',
                'smtp_user',
                'smtp_pass',
                'smtp_port',
                'send_mails_as',
                css_class="card my-3 my-md-5 p-3"
            )
        )

        self.helper.add_input(Submit('save-options', 'Save Options'))

cms/apps/dashboard/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.http import Http404, HttpResponse
from django.shortcuts import render
from rolepermissions.checkers import has_permission, has_role
from rolepermissions.roles import assign_role, clear_roles, get_user_roles

from apps.accounts import roles as r
from apps.accounts.models import User
from apps.accounts.roles import Admin, Subscriber
from apps.core.constants import database_keys as dk
from apps.core.constants import permissions as p
from apps.core.utils import getOptions, setOption, getOption

from .forms import OptionsForm, PasswordChangeForm, RolesForm, UserForm
from .utils import getTableDataForUsers


@login_required
def IndexView(request):
    if has_role(request.user, Admin):
        context = {
            "count": {
                "users": User.objects.all().count()
            }
        }
        return render(request, "dashboard/index.html", {"data": context})
    elif has_role(request.user, Subscriber):
        return render(request, "dashboard/index-subscriber.html")
    else:
        raise PermissionDenied("You are not allowed to access this page!")


def BrowseUsersView(request):
    if has_permission(request.user, p.READ_USERS):
        enabled_columns = None
        sort_by = None
        sort_order = None
        search = None
        if request.GET.get('enabled_columns', False):
            enabled_columns = request.GET.getlist('enabled_columns')
        if request.GET.get('sort_by', False):
            sort_by = request.GET.get('sort_by')
        if request.GET.get('sort_order', False):
            sort_order = request.GET.get('sort_order')
        if request.GET.get('search', False):
            search = request.GET.get('search')

        tableData = getTableDataForUsers(enabled_columns=enabled_columns,
                                         search=search,
                                         sort_by=sort_by,
                                         sort_order=sort_order
                                         )
        return render(request, "dashboard/list.html", {"tableData": tableData})
    else:
        raise PermissionDenied("You are not allowed to List Users.")


@login_required
def UserEditView(request, userid=None):

    form = None
    user = None
    passForm = None
    rolesForm = None

    if userid == None:
        user = request.user
    elif has_permission(request.user, p.EDIT_USERS) or request.user.id == userid:
        try:
            user = User.objects.get(id=userid)
        except ObjectDoesNotExist as e:
            raise Http404("User Does Not Exist")
    else:
        raise PermissionDenied(
            "You do not have permission to edit/view this user")

    if has_permission(request.user, p.EDIT_USERS):
        roles = []
        for x in get_user_roles(user):
            roles.append(x.display_name)
        rolesForm = RolesForm({'roles': roles})

    form = UserForm(user=request.user, instance=user)
    passForm = PasswordChangeForm(user)

    if request.method == "POST":
        if 'user-submit' in request.POST:
            form = UserForm(user=request.user, data=request.POST or None,
                            files=request.FILES or None, instance=user)
            if form.is_valid():
                form.save()

        if 'password-change' in request.POST:
            passForm = PasswordChangeForm(user, request.POST or None)
            if passForm.is_valid():
                passForm.save()
                update_session_auth_hash(request, user)

        if 'change-role' in request.POST:
            rolesForm = RolesForm(request.POST or None)
            if rolesForm.is_valid():
                User().change_user_role(user, rolesForm.cleaned_data['roles'])

    return render(request, "dashboard/edit-user.html", {'form': form, 'user_context': user, 'passform': passForm, 'rolesForm': rolesForm})


@login_required
def ManageSiteView(request):
    if has_role(request.user, Admin):
        form = None
        if request.method == "POST":
            form = OptionsForm(data = request.POST, files = request.FILES or None)
            if form.is_valid():
                for data in form.cleaned_data:
                    setOption(data, form.cleaned_data[data])
        else:
            form = OptionsForm(initial=getOptions())
        return render(request, "dashboard/settings.html", {"form": form})
    else:
        raise PermissionDenied(
            "You do not have permissions to access this page!")

@login_required
def TestView(request):

    from apps.core.utils import send_mail

    return HttpResponse(send_mail("Test Mail", ["thisisayushaa@gmail.com"], "Test Mail Success!"))

cms/apps/dashboard/templates/dashboard/_base.html
{% extends '_base.html' %}
{% block title %}{% endblock %}

{% block page %}
      {% include "preloader.html" %}
      <div class="page-main">
        {% include "dashboard/components/_header.html" %}
        {% block content %}
        {% endblock %}
      </div>
      {% include "dashboard/components/_footer.html" %}
{% endblock %}

cms/apps/dashboard/templates/dashboard/_base_left_sidebar.html
{% extends 'dashboard/_base.html' %}

{% block content %}
      <div class="my-3 my-md-5">
        <div class="container">
          <div class="row flex-column-reverse flex-lg-row">
            <div class="col-lg-4 sidebar" style="position: relative;">
              {% block sidebar %}{% endblock %}
            </div>
            <div class="col-lg-8">
              {% block content_block %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
{% endblock %}

cms/apps/dashboard/templates/dashboard/_list-table.html
<div class="table-responsive">
        <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
            <thead>
                <tr>
                    {% for field in tableData.fields %}
                    <th class="{{ field.class }}">{% if field.label != "..." %}{{ field.label }}{% endif %}</th>
                    {% endfor %}
                    <th class="w-1"></th>
                </tr>
            </thead>
            <tbody>
                {% if tableData.rows|length == 0 %}
                <tr>
                    <td colspan="{{ tableData.fields|length|add:"1" }}" class="text-center text-secondary">No Entries Found</td>
                </tr>
                {% endif %}
                {% for row in tableData.rows %}
                <tr data-id="{{ row.id }}" id="row-{{ row.id }}">
                    {% for data in row.data %}
                    <td>
                        {% if data.type == "progress-meter" %}
                            <div class="clearfix">
                                <div class="float-left">
                                    <strong>{{ data.meta.percent }}%</strong>
                                </div>
                                {% if data.subtext %}
                                <div class="float-right">
                                    <small class="text-muted">
                                        {{ data.subtext }}
                                    </small>
                                </div>
                                {% endif %}
                            </div>
                            <div class="progress progress-xs">
                                <div class="progress-bar {% if data.meta.percent < 40 %}bg-red{% elif data.meta.percent < 70 %}bg-yellow{% else %}bg-green{% endif %}" role="progressbar" style="width:{{ data.meta.percent }}%" aria-valuenow="{{ data.meta.percent }}" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        {% elif data.type == "text" %}
                            <div>{{ data.text }}</div>
                            {% if data.subtext %}
                                <div class="small text-muted">{{ data.subtext }}</div>
                            {% endif %}
                        {% elif data.type == "link" %}
                            <div><a href="{{ data.text }}">{{ data.text|truncatechars:20 }}</a></div>
                            {% if data.subtext %}
                                <div class="small text-muted">{{ data.subtext }}</div>
                            {% endif %}
                        {% elif data.type == "currency" %}
                            <div><i class="fa fa-rupee" style="font-size: 0.85em;"></i> {{ data.text }}</div>
                        {% if data.subtext %}
                            <div class="small text-muted">{{ data.subtext }}</div>
                        {% endif %}
                        {% elif data.type == "text-inverted" %}
                            {% if data.subtext %}
                                <div class="small text-muted">{{ data.subtext }}</div>
                            {% endif %}
                            <div>{{ data.text }}</div>
                        {% elif data.type == "text-secondary" %}
                            <span class="text-muted">{{ data.text }}</span>
                        {% elif data.type == "avatar" %}
                            <div class="avatar d-block" style="background-image: url('{{ data.meta.url }}')">
                                {% if data.meta.status %}
                                <span class="avatar-status {% if data.meta.status == '1' %}bg-green{% else %}bg-red{% endif %}"></span>
                                {% endif %}
                            </div>
                        {% elif data.type == "icon" %}
                            <i class="{{ data.meta.iconclass }}"></i>
                        {% endif %}
                    </td>
                    {% endfor %}
                    <td class="action-buttons text-right">
                        {% for action in row.actions %}
                        <a href="{{ action.url }}?next={{ request.path }}" class="btn btn-sm {{ action.btn_class }}">{{ action.label }}</a>
                        {% endfor %}
                        {% comment %} <a href="{% url 'dashboard:edit-user' user.id %}" class="btn btn-secondary btn-sm">Edit</a> {% endcomment %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

cms/apps/dashboard/templates/dashboard/edit-user.html
{% extends 'dashboard/_base.html' %}
{% load crispy_forms_tags %}
{% load permission_tags %}
{% load static %}

{% block title %}Edit User{% endblock %}

{% block header_js %}
{{ form.media }}
{% endblock %}

{% block content %}
    <div class="my-3 my-md-5">
        <div class="card w-75 mx-auto">
            <div class="card-header">
                Edit User
            </div>
            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="col-5 mx-auto text-center">
                            <span class="avatar avatar-xxl" style="background-image:url('{% if user_context.avatar %}{{ user_context.avatar.url }}{% else %}{% static 'assets/images/avatar.png' %}{% endif %}')"></span>
                        </div>
                    </div>
                    {% if user|can:constants.permissions.EDIT_USERS %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100 my-3">
                            <div class="form-row align-items-center">
                                <div class="col-12 col-sm-6 form-group align-items-center">
                                    <label class="form-label">User Id</label>
                                    <div class="form-control-plaintext">{{ user_context.id }} {% if user_context.is_active %}(Active){% else %}(Inactive){% endif %}</div>
                                </div>
                                <div class="col-12 col-sm-6 align-items-center">
                                    <label class="form-label">Member Since</label>
                                    <div class="form-control-plaintext">{{ user_context.date_joined }}</div>
                                </div>
                                <div class="col-12 col-sm-6 align-items-center">
                                    <label class="form-label">Last Login</label>
                                    <div class="form-control-plaintext">{{ user_context.last_login }}</div>
                                </div>
                                <div class="col-12 col-sm-6 align-items-center">
                                    <label class="form-label">Email Confirmed</label>
                                    <div class="form-control-plaintext">{{ user_context.email_confirmed }}</div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    {% endif %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100 my-3">
                            {% crispy form form.helper %}
                        </fieldset>
                    </div>
                    <div class="row">
                        <fieldset class="form-fieldset w-100">
                            {% crispy passform %}
                        </fieldset>
                    </div>
                    {% if rolesForm is not None %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100">
                            {% crispy rolesForm %}
                        </fieldset>
                    </div>
                    {% endif %}
                    {% if user|can:constants.permissions.SUSPEND_USERS %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100">
                                {% if user_context.is_active %}
                                <a href="{% if user == user_context %}#{% else %}{% url 'dashboard:suspend-user' user_context.id %}?next={{ request.path }}{% endif %}"><button class="btn btn-danger" {% if user == user_context %}disabled{% endif %}>Suspend Login</button></a>
                                {% else %}
                                <a href="{% url 'dashboard:enable-user' user_context.id %}?next={{ request.path }}"><button class="btn btn-primary">Enable Login</button></a>
                                {% endif %}
                                <a href="{% if user == user_context %}#{% else %}{% url 'dashboard:remove-user' user_context.id %}{% endif %}"><button class="btn btn-danger" {% if user == user_context %}disabled{% endif %}>Remove User</button></a>
                                {% if not user_context.email_confirmed %}
                                <a href="{% url 'dashboard:activate-user' user_context.id %}"><button class="btn btn-warning">Mark email as Confirmed</button></a>
                                {% endif %}
                        </fieldset>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cms/apps/dashboard/templates/dashboard/index-subscriber.html
{% extends "dashboard/_base.html" %}
{% load static %}
{% block title %}Home | Student Dashboard{% endblock %}

{% block content %}
<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            <h1 class="page-title">
                Dashboard
            </h1>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="card card-profile text-center">
                    <div class="card-header" style="background-image:url('https://picsum.photos/500/300')"></div>
                    <div class="card-body">
                        <img class="card-profile-img" src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'assets/images/avatar.png' %}{% endif %}">
                        <h3 class="mb-3">{{ user.get_full_name }}</h3>
                        <p class="text-secondary">{{ user.email }}</p>
                        <a class="btn btn-outline-primary btn-sm" href="{% url 'dashboard:profile' %}">Edit Profile</a>
                    </div>
                </div>
                <div class="card">
                    <a href="mailto://{{ meta.support_email }}" class="btn btn-secondary bg-teal">
                    <div class="card-body text-white text-center">
                        <span class="fa fa-support fa-2x mr-3"></span> <span class="fa-2x">Contact Support</span>
                    </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="page-header mt-0">
                    <h1 class="page-title">
                        Quick Access
                    </h1>
                    </div>
                    <div class="row row-cards button-cards">
                    <div class="col-6 col-sm-3">
                        <div class="card">
                        <a href="{% url 'accounts:logout' %}" class="btn btn-dark" style="font-size: 1.2em;">
                        <div class="card-body p-3 text-center">
                            <span class="fe fe-log-out"></span> Logout
                        </div>
                        </a>
                        </div>
                    </div>
                    </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

cms/apps/dashboard/templates/dashboard/index.html
{% extends "dashboard/_base.html" %}

{% block title %}Home | Dashboard{% endblock %}
{% block content %}
    <div class="my-3 my-md-5">
        <div class="container">
          <div class="page-header">
            <h1 class="page-title">
              Quick Access
            </h1>
          </div>
          <div class="row row-cards button-cards">
            <div class="col-6 col-sm-3">
              <div class="card">
                <a href="{% url 'dashboard:list-users' %}" class="btn btn-dark" style="font-size: 1.2em;">
                <div class="card-body p-3 text-center">
                  <span class="fe fe-user"></span> Users
                </div>
                </a>
              </div>
            </div>
            <div class="col-6 col-sm-3">
              <div class="card">
                <a href="#" class="btn btn-dark" style="font-size: 1.2em;">
                <div class="card-body p-3 text-center">
                  <span class="fe fe-server"></span> Settings
                </div>
                </a>
              </div>
            </div>
            <div class="col-6 col-sm-3">
              <div class="card">
                <a href="{% url 'accounts:logout' %}" class="btn btn-dark" style="font-size: 1.2em;">
                <div class="card-body p-3 text-center">
                  <span class="fe fe-log-out"></span> Logout
                </div>
                </a>
              </div>
            </div>
          </div>
          <div class="page-header">
            <h1 class="page-title">
              Dashboard
            </h1>
          </div>
          <div class="row row-cards">
            <div class="col-6 col-sm-4 col-lg-2">
              <div class="card">
                <div class="card-body p-3 text-center">
                  <div class="h1 m-0">{{ data.count.users|default:"Error" }}</div>
                  <div class="text-muted mb-4">Registered Users</div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
{% endblock %}

cms/apps/dashboard/templates/dashboard/list-single.html
{% extends 'dashboard/_base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="my-3 my-md-5">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <form>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Type to search.." name="search" value="{{ tableData.meta.search }}">
                            <span class="input-group-append">
                                <span class="input-group-btn"><button class="btn btn-primary" type="submit"><i class="fe fe-search"></i></button></span>
                            </span>
                        </div>
                        </form>
                    </div>
                </div>
                <div class="col-12 my-3 my-md-5">
                    <div class="card card-table">
                        {% include 'dashboard/_list-table.html' %}
                        <!-- <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
                                        {% for column in tableData.fields %}
                                        <th class="{{ column.class }}">{{ column.label }}</th>
                                        {% endfor %}
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for row in tableData.rows %}
                                        <tr>
                                            {% for data in row.data %}
                                            <td>{{ data }}</td>
                                            {% endfor %}
                                            <td>
                                                {% for action in row.actions %}
                                                <a class="btn btn-{{ action.class }}" href="{{ action.url }}">{{ action.title }}</a>
                                                {% endfor %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}