cms/apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView, name="login"),
    path('register/', UserSignupView, name="register"),
    path('logout/', LogoutView, name="logout"),
    path('checkLogin/', isUserLoggedIn, name="check-login"),
    path("forgot-password/", PasswordResetView, name="password_reset"),
    path("forgot-password/validate/<uidb64>/<token>/", PasswordResetTokenValidateView, name="password_reset_confirm"),
    path("register/activate/<uidb64>/<token>/", ActivateAccountTokenValidateView, name="activate-account"),
    path("register/resend-activation/", ResendAccountActivationView, name="resend-account-activation"),
    path('get/users/autocomplete', AutocompleteUsersListView, name="get-autocomplete-users-list"),
]

cms/apps/dashboard/urls.py
from django.urls import path, include
from apps.accounts.views import EnableUser, RemoveUser, SuspendUser, ActivateUser

from . import views as v

app_name = "dashboard"

urlpatterns = [
    path("users/browse/", v.BrowseUsersView, name="list-users"),
    path("profile/", v.UserEditView, name="profile"),
    path("settings/", v.ManageSiteView, name="site-management"),
    path("settings/users/manage/edit/<int:userid>/", v.UserEditView, name="edit-user"),
    path("settings/users/manage/suspend/<int:userid>/", SuspendUser, name="suspend-user"),
    path("settings/users/manage/enable/<int:userid>/", EnableUser, name="enable-user"),
    path("settings/users/manage/remove/<int:userid>/", RemoveUser, name="remove-user"),
    path("settings/users/manage/activate/<int:userid>/", ActivateUser, name="activate-user"),
    path("od/", include("apps.odmanager.urls", namespace="od")),
    path("", v.IndexView, name="home"),
]

cms/cms/urls.py
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    path("c/", include('apps.club.urls', namespace="club")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'
handler400 = 'apps.core.views.bad_request'

cms/apps/accounts/forms.py
from crispy_forms.bootstrap import InlineRadios
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Div, Field, Layout, Submit
from django import forms
from django.core.exceptions import ValidationError
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ModelForm
from .models import User
from django.core.validators import validate_email
from .utils import UserExistsByEmail
from apps.core.models import *
from apps.core.widgets import DatePickerInput

class LoginForm(forms.Form):

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput,
        label="Email"
    )

    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput,
        label="Password"
    )

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"
        self.helper.form_error_title = "Oops"
        self.helper.add_input(
            Submit('login', 'Login', css_class="btn-block")
        )


class UserSignupForm(ModelForm):

    first_name = forms.CharField(
        required=True
    )
    last_name = forms.CharField(
        required=True
    )
    gender = forms.ChoiceField(
        choices=User.gender_choices,
        widget=forms.widgets.RadioSelect,
        help_text="Select your gender, wisely."
    )
    date_of_birth = forms.DateField(
        widget=DatePickerInput()
    )
    mobile = forms.CharField(
        required = True,
        label = 'Mobile Number',
        help_text="WhatsApp Preferred."
    )
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput,
        label='Password'
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'gender',
            'mobile',
            'avatar',
            'enrollment_no',
            'date_of_birth',
            'registration_year',
            'department',
            'branch',
            'section',
            'batch',
        ]

    def __init__(self, *args, **kwargs):
        super(UserSignupForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_class = "container"
        self.helper.label_class = "font-weight-bold"

        self.helper.layout = Layout(
            Div(
                Field('first_name', wrapper_class="col-12 col-md-6"),
                Field('last_name', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            Div(
                Field('mobile', wrapper_class="col-12 col-md-6"),
                Field('email', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            'password1',
            Div(
                InlineRadios('gender', wrapper_class="col-12 col-md-6"),
                Field('date_of_birth', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            Field('avatar'),
            Div(
                Field('enrollment_no', wrapper_class="col-12 col-md-6"),
                Field('registration_year', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            Div(
                Field('department', wrapper_class="col-12 col-md-3"),
                Field('branch', wrapper_class="col-12 col-md-3"),
                Field('section', wrapper_class="col-6 col-md-3"),
                Field('batch', wrapper_class="col-6 col-md-3"),
                css_class="row"
            ),
            HTML(
                '<div class="my-3">By Signing up, you automatically agree to our <a href="#">Terms and Conditions</a>.</div>',
            )
        )
        self.helper.add_input(
            Submit('register', 'Create New Account', css_class="btn-block")
        )

    def save(self, commit=True):
        m = super(UserSignupForm, self).save(commit=False)

        m.set_password(self.cleaned_data['password1'])

        if commit:
            m.save()
        return m
    
    def clean_branch(self):
        valid_branches = DepartmentBranches.objects.filter(department = self.cleaned_data['department'])
        
        if self.cleaned_data['branch'] not in valid_branches:
            raise ValidationError("Invalid Branch for selected department")
        return self.cleaned_data['branch']
    

class EmailCollectionForm(forms.Form):

    email = forms.EmailField(label="Enter your email", required=True)

    def __init__(self, *args, **kwargs):
        super(EmailCollectionForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()

        self.helper.label_class = "font-weight-bold"
        self.helper.form_error_title = "Oops"
        self.helper.add_input(
            Submit('submit', 'Submit', css_class="btn-block")
        )
    
    def clean_email(self):

        validate_email(self.cleaned_data['email'])

        if not UserExistsByEmail(self.cleaned_data['email']):
            raise ValidationError("An account with the given email doesn't exist")

        return self.cleaned_data['email']

cms/apps/accounts/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import redirect, render, reverse
from rolepermissions.checkers import has_permission
from rolepermissions.roles import assign_role

from apps.core.constants import permissions as p

from .forms import LoginForm, UserSignupForm, EmailCollectionForm
from .models import User
from .roles import Subscriber
from .utils import *
from apps.dashboard.forms import PasswordChangeForm

def isUserLoggedIn(request):
    if request.user.is_authenticated:
        return HttpResponse(True)
    else:
        return HttpResponse(False)

def LoginView(request):
    if request.user.is_authenticated:
        return redirect(settings.LOGIN_REDIRECT_URL)
    form = None
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request, email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            if user is not None:
                if user.email_confirmed == True or user.is_superuser:
                    login(request, user)
                    return redirect(request.GET.get('next') if request.GET.get('next', False) else settings.LOGIN_REDIRECT_URL)
                else:
                    form.add_error(None, "Your account isn't activated. Please Check your email for activation mail or send a new one.")
            else:
                try:
                    user = User.objects.get(email=form.cleaned_data['email'])
                    if not user.is_active:
                        form.add_error(
                            None, "Your Login has been suspended. Contact Support for further info.")
                    else:
                        form.add_error(
                            None, "Username and Password doesn't match. Re-check the details. Password is case-sensitive.")
                except ObjectDoesNotExist as e:
                    form.add_error(
                        None, "No account exists with the given email.")
    else:
        form = LoginForm()
    
    loggedout = False
    if request.GET.get("loggedout"):
        loggedout = True
    return render(request, 'accounts/login.html', {'form': form, "logged_out": loggedout})


def LogoutView(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    logout(request)
    return redirect("%s?loggedout=true"%settings.LOGIN_URL)


def UserSignupView(request):
    if request.user.is_authenticated:
        return redirect(settings.LOGIN_REDIRECT_URL)
    
    if request.method == "POST":
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            assign_role(user, Subscriber)
            user = authenticate(
                email=request.POST['email'], password=request.POST['password1'])

            if user is not None:
                if SendAccountActivationEmail(user.email):
                    return render(request, "success.html", {"message": "Account created successfully! Please check your email for activation email to activate your account."})
                else:
                    return render(request, "error.html", {"message": "Unable to send Account Activation Email. Contact Support."})
    else:
        form = UserSignupForm()
    if request.GET.get("via"):
        via = request.GET.get("via")
    else:
        via = False
    return render(request, 'accounts/register.html', {'form': form, 'via': via})


def PasswordResetView(request):
    logout(request)
    form = None
    if request.method == "POST":
        form = EmailCollectionForm(request.POST)
        if form.is_valid():
            res = sendPasswordResetEmail(form.cleaned_data['email'])
            if res:
                return render(request, "accounts/mail-sent.html")
    else:
        form = EmailCollectionForm()

    return render(request, "accounts/forgot-password.html", {"form": form})

def ResendAccountActivationView(request):
    logout(request)
    form = None
    if request.method == "POST":
        form = EmailCollectionForm(request.POST)
        if form.is_valid():
            res = SendAccountActivationEmail(form.cleaned_data['email'])
            if res:
                return render(request, "accounts/mail-sent.html", {"action": "Activate your Account"})
    else:
        form = EmailCollectionForm()

    return render(request, "accounts/account-activation.html", {"form": form})

def PasswordResetTokenValidateView(request, uidb64=None, token=None):

    if uidb64 is None or token is None:
        raise Http404("Page not found!")
    
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist) as e:
        return render(request, "error.html", {"error": e})
    
    form = PasswordChangeForm(user)
    
    if request.method == "POST":
    
        if PasswordResetTokenGenerator().check_token(user, token):
            form = PasswordChangeForm(user, request.POST)
            if form.is_valid():
                form.save()
                return render(request, "success.html", {"message": "Password Updated Successfuly!"})
        else:
            return render(request, "error.html", {"error": "The Reset Link is no longer valid. Generate a new one."})
    
    return render(request, "accounts/forgot-password-change.html", {"token": token, 'form': form})

def ActivateAccountTokenValidateView(request, uidb64=None, token=None):

    if uidb64 is None or token is None:
        raise Http404("Page not found!")
    
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist) as e:
        return render(request, "error.html", {"error": e})
    
    if AccountActivationTokenGenerator().check_token(user, token):
        if ActivateUserAccount(user):
            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            return render(request, "error.html", {"error": "Unknown Error Occured while activating your account."})
    else:
        return render(request, "error.html", {"error": "The Activation Link is no longer valid. Generate a new one."})

    return render(request, "accounts/forgot-password-change.html", {"token": token, 'form': form})

@login_required
def SuspendUser(request, userid):

    if has_permission(request.user, p.SUSPEND_USERS):
        try:
            user = User.objects.get(pk=userid)
            if user == request.user:
                raise PermissionDenied("Cannot Set Current User as Inactive")
            user.is_active = False
            user.save()
            return redirect(request.GET.get('next') if request.GET.get('next', False) else reverse('dashboard:edit-user', args=[user.id]))
        except ObjectDoesNotExist as e:
            raise Http404("User doesn't exist.")
    else:
        raise PermissionDenied(
            "You do not have permissions to suspend/enable users.")


@login_required
def EnableUser(request, userid):

    if has_permission(request.user, p.SUSPEND_USERS):
        try:
            user = User.objects.get(pk=userid)
            user.is_active = True
            user.save()
            return redirect(request.GET.get('next') if request.GET.get('next', False) else reverse('dashboard:edit-user', args=[user.id]))
        except ObjectDoesNotExist as e:
            raise Http404("User doesn't exist")
    else:
        raise PermissionDenied(
            "You do not have permissions to suspend/enable users.")

@login_required
def ActivateUser(request, userid):

    if has_permission(request.user, p.SUSPEND_USERS):
        try:
            user = User.objects.get(pk=userid)
            user.email_confirmed = True
            user.save()
            return redirect(request.GET.get('next') if request.GET.get('next', False) else reverse('dashboard:edit-user', args=[user.id]))
        except ObjectDoesNotExist as e:
            raise Http404("User doesn't exist")
    else:
        raise PermissionDenied(
            "You do not have permissions to activate users.")


@login_required
def RemoveUser(request, userid):

    if has_permission(request.user, p.DELETE_USERS):
        if request.method == "GET":
            return render(
                request,
                'confirm-action.html',
                {
                    'action': 'Delete User',
                    'value': userid,
                    'key': 'id'
                }
            )
        if 'yes' in request.POST:
            try:
                user = User.objects.get(id=userid)
                if request.user == user:
                    raise PermissionDenied(
                        "Deletion of self accounts is banned!")
                user.delete()
                return redirect(request.GET.get('next') if request.GET.get('next', False) else reverse('dashboard:list-users'))
            except User.DoesNotExist:
                raise Http404("User Doesn't Exist")
        else:
            return redirect(reverse('dashboard:list-users'))
    else:
        raise PermissionDenied("You Do not have permissions to remove users.")

@login_required
def AutocompleteUsersListView(request): 

    if has_permission(request.user, p.READ_USERS):
        users = []
        if request.GET.get('term', False):
            term = request.GET.get('term')
            users = User.filter_user_data(search=term)
        else:
            users = User.objects.all()
        data = []
        for user in users:
            obj = {}
            obj['id'] = user.id
            obj['value'] = user.email

cms/apps/accounts/templates/accounts/_base.html
{% extends '_base.html' %}

cms/apps/accounts/templates/accounts/account-activation.html
{% extends 'accounts/_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Forgot Password{% endblock %}

{% block page %}
  <div class="page-single">
    <div class="container">
      <div class="row">
        <div class="col col-login mx-auto">
          <div class="text-center mb-6">
            <img src="{% static 'assets/images/clubpress-logo-black-full.png' %}" class="h-6" alt="">
          </div>
          <div class="card p-3">
            <div class="card-header">
              <h3 class="card-title">Resend Activation Mail</h3>
            </div>
            <div class="card-body">
            {% crispy form %}
            </div>
          </div>
          <div class="text-center text-muted">
            Forget it, <a href="{% url 'accounts:login' %}">send me back</a> to the sign in screen.
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

cms/apps/accounts/templates/accounts/forgot-password-change.html
{% extends 'accounts/_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Forgot Password{% endblock %}

{% block page %}
  <div class="page-single">
    <div class="container">
      <div class="row">
        <div class="col col-login mx-auto">
          <div class="text-center mb-6">
            <img src="{% static 'assets/images/clubpress-logo-black-full.png' %}" class="h-6" alt="">
          </div>
          <div class="card p-3">
              <div class="card-header">
                <h3 class="card-title">Reset your password</h3>
              </div>
              <div class="form-group">
                <label class="form-label">Token:</label>
                <input class="form-control" value="{{ token }}" disabled>
              </div>
              {% crispy form %}
          </div>
          <div class="text-center text-muted">
            Forget it, <a href="{% url 'accounts:login' %}">send me back</a> to the sign in screen.
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

cms/apps/accounts/templates/accounts/forgot-password.html
{% extends 'accounts/_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Forgot Password{% endblock %}

{% block page %}
  <div class="page-single">
    <div class="container">
      <div class="row">
        <div class="col col-login mx-auto">
          <div class="text-center mb-6">
            <img src="{% static 'assets/images/clubpress-logo-black-full.png' %}" class="h-6" alt="">
          </div>
          <div class="card p-3">
            <div class="card-header">
              <h3 class="card-title">Forgot Password</h3>
            </div>
            <div class="card-body">
            {% crispy form %}
            </div>
          </div>
          <div class="text-center text-muted">
            Forget it, <a href="{% url 'accounts:login' %}">send me back</a> to the sign in screen.
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

cms/apps/accounts/templates/accounts/login.html
{% extends 'accounts/_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}
{% block page %}
      <div class="page-single">
        <div class="container">
          <div class="row">
            <div class="col col-login mx-auto">
              <div class="text-center mb-6">
                <a href="{% url 'dashboard:home' %}" ><img src="{% static 'assets/images/clubpress-logo-black-full.png' %}" class="h-8" alt="logo"></a>
              </div>
              <div class="card">
                <div class="card-body p-6">
                  <div class="card-title text-center">Login to your account</div>
                    {% if logged_out %}
                      <div class="alert alert-success text-center">You have been logged out.</div>
                    {% endif %}
                    {% crispy form %}
                </div>
              </div>
              <div class="text-center text-muted">
                <a href="{% url 'accounts:register' %}" class="mx-3">Sign up</a> | <a class="mx-3" href="{% url 'accounts:password_reset' %}">Forgot Password</a> | <a class="mx-3" href="{% url 'accounts:resend-account-activation' %}">Resend Activation</a>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

cms/apps/accounts/templates/accounts/mail-sent.html
{% extends 'accounts/_base.html' %}
{% load static %}
{% block title %}Forgot Password{% endblock %}

{% block page %}
  <div class="page-single">
    <div class="container">
      <div class="row">
        <div class="col col-login mx-auto">
          <div class="text-center mb-6">
            <img src="{% static 'assets/images/clubpress-logo-black-full.png' %}" class="h-6" alt="">
          </div>
          <div class="card">
              <div class="card-body">
                  We have sent you an email with a magic link. Click on the link to {{ action }}.
              </div>
          </div>
          <div class="text-center text-muted">
            Take me back to <a href="{% url 'accounts:login' %}">Login</a> screen.
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

cms/apps/accounts/templates/accounts/register.html
{% extends 'accounts/_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Register{% endblock %}

{% block page %}
<div class="page-single">
  <div class="container">
    <div class="row">
      <div class="col col-md-8 mx-auto">
        <div class="text-center mb-6">
            <a href="{% url 'dashboard:home' %}" ><img src="{% static 'assets/images/clubpress-logo-black-full.png' %}" class="h-8" alt="Logo"></a>
        </div>
        <div class="card">
          <div class="card-body p-6">
            <div class="card-title text-center font-weight-bold">
              Create new account
            </div>
            {% crispy form %}
          </div>
        </div>
        <div class="text-center text-muted">
          Already have account?
          <a href="{% url 'accounts:login' %}">Sign in</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}