cms/apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView, name="login"),
    path('register/', UserSignupView, name="register"),
    path('logout/', LogoutView, name="logout"),
    path('checkLogin/', isUserLoggedIn, name="check-login"),
    path("forgot-password/", PasswordResetView, name="password_reset"),
    path("forgot-password/validate/<uidb64>/<token>/", PasswordResetTokenValidateView, name="password_reset_confirm"),
    path("register/activate/<uidb64>/<token>/", ActivateAccountTokenValidateView, name="activate-account"),
    path("register/resend-activation/", ResendAccountActivationView, name="resend-account-activation"),
    path('get/users/autocomplete', AutocompleteUsersListView, name="get-autocomplete-users-list"),
]

cms/apps/dashboard/urls.py
from django.urls import path, include
from apps.accounts.views import EnableUser, RemoveUser, SuspendUser, ActivateUser

from . import views as v

app_name = "dashboard"

urlpatterns = [
    path("users/browse/", v.BrowseUsersView, name="list-users"),
    path("profile/", v.UserEditView, name="profile"),
    path("settings/", v.ManageSiteView, name="site-management"),
    path("settings/users/manage/edit/<int:userid>/", v.UserEditView, name="edit-user"),
    path("settings/users/manage/suspend/<int:userid>/", SuspendUser, name="suspend-user"),
    path("settings/users/manage/enable/<int:userid>/", EnableUser, name="enable-user"),
    path("settings/users/manage/remove/<int:userid>/", RemoveUser, name="remove-user"),
    path("settings/users/manage/activate/<int:userid>/", ActivateUser, name="activate-user"),
    path("od/", include("apps.odmanager.urls", namespace="od")),
    path("", v.IndexView, name="home"),
]

cms/cms/urls.py
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    path("c/", include('apps.club.urls', namespace="club")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'
handler400 = 'apps.core.views.bad_request'

cms/apps/dashboard/models.py
from django.db import models

# Create your models here.

cms/apps/dashboard/forms.py
from crispy_forms.bootstrap import InlineRadios
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout, Submit
from django import forms
from django.contrib.auth.forms import AdminPasswordChangeForm
from rolepermissions.checkers import has_permission
from django.core.exceptions import ValidationError
from apps.accounts.models import User
from apps.core.constants import permissions as p
from apps.accounts.roles import Subscriber, Admin
from apps.core.models import Departments, DepartmentBranches
import datetime
class UserForm(forms.ModelForm):

    gender = forms.ChoiceField(
        choices=User.gender_choices,
        widget = forms.RadioSelect
    )

    mobile = forms.CharField(
        label = "Mobile Number"
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'gender', 'avatar', 'mobile', 'date_of_birth', 'enrollment_no', 'registration_year', 'department', 'branch', 'section', 'batch']

    def __init__(self, user, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "container"
        self.helper.label_class = "font-weight-bold"
        # edit_sensitive_fields = True if has_permission(user, p.EDIT_USERS) else False
        edit_sensitive_fields = False
        emailField = Field('email', wrapper_class="col-12 col-md-6")

        if not edit_sensitive_fields:
            emailField = Field('email', readonly=edit_sensitive_fields, wrapper_class="col-12 col-md-6")
            
        self.helper.layout = Layout(
            Div(
                Field('first_name', wrapper_class='col-12 col-md-6'),
                Field('last_name', wrapper_class='col-12 col-md-6'),
                css_class="row"
            ),
            Div(
                emailField,
                Field('mobile', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            Div(
                InlineRadios('gender', wrapper_class="col-12 col-md-6"),
                Field('date_of_birth', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            'avatar',
            Div(
                Field('enrollment_no', wrapper_class="col-12 col-md-6"),
                Field('registration_year', wrapper_class="col-12 col-md-6"),
                css_class="row"
            ),
            Div(
                Field('department', wrapper_class="col-12 col-md-3"),
                Field('branch', wrapper_class="col-12 col-md-3"),
                Field('section', wrapper_class="col-6 col-md-3"),
                Field('batch', wrapper_class="col-6 col-md-3", read_only=edit_sensitive_fields),
                css_class="row"
            ),
        )
        self.helper.add_input(Submit('user-submit', 'Save'))

    def clean_branch(self):
        valid_branches = DepartmentBranches.objects.filter(department = self.cleaned_data['department'])

        if self.cleaned_data['branch'] not in valid_branches:
            raise ValidationError("Invalid Branch for selected department")
        return self.cleaned_data['branch']

    def clean_registration_year(self):
        try:
            year = int(self.cleaned_data['registration_year'])
        except ValueError:
            raise ValidationError("Please enter a valid year!")
        
        if year < 2005 or year > datetime.datetime.now().year:
            raise ValidationError("Value must be greater than 2002 and less than current year!")
        
        return self.cleaned_data['registration_year']

    def clean_section(self):
        try:
            section = int(self.cleaned_data['section'])
        except ValueError:
            raise ValidationError("Please enter a valid section!")
        
        if section < 1 or section > 99:
            raise ValidationError("Please enter a valid section!")

        return self.cleaned_data['section']
    
    def clean_batch(self):
        if len(self.cleaned_data['batch']) > 1:
            raise ValidationError('Enter a valid batch!')
        
        return self.cleaned_data['batch']
    
    def clean_mobile(self):
        if len(self.cleaned_data['mobile']) > 10:
            raise ValidationError('Enter a valid mobile number!')
        for digit in self.cleaned_data['mobile']:
            try:
                int(digit)
            except ValueError as e:
                raise ValidationError("Enter a valid mobile number")
        
        return self.cleaned_data['mobile']

class PasswordChangeForm(AdminPasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.pop("autofocus", None)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"
        
        self.helper.add_input(Submit('password-change', 'Change Password'))

class RolesForm(forms.Form):

    roles = forms.MultipleChoiceField(
        choices = (
            (Subscriber.display_name, Subscriber.title),
            (Admin.display_name, Admin.title)
        )
    )

    def __init__(self, *args, **kwargs):
        super(RolesForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"

        self.helper.add_input(Submit('change-role', 'Save Role(s)'))

class OptionsForm(forms.Form):

    site_title = forms.CharField(label = "Site Title", required=False)
    site_description = forms.CharField(label = "Site Description",required = False)
    support_email = forms.EmailField(label = "Support Email", required=False)
    site_url = forms.URLField(label = "Site URL", required=True)
    smtp_server = forms.CharField(label = "SMTP Server")
    smtp_user = forms.CharField(label = "SMPT User")
    smtp_pass = forms.CharField(label = "SMTP Password")
    smtp_port = forms.CharField(label = "SMTP Port")
    send_mails_as = forms.EmailField(label = "Send Email As")

    def __init__(self, *args, **kwargs):
        super(OptionsForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"
        
        self.helper.layout = Layout(
            Div(
                'site_title',
                'site_url',
                'site_description',
                'support_email',
                css_class="card my-3 my-md-5 p-3"
            ),
            Div(
                'smtp_server',
                'smtp_user',
                'smtp_pass',
                'smtp_port',
                'send_mails_as',
                css_class="card my-3 my-md-5 p-3"
            )
        )

        self.helper.add_input(Submit('save-options', 'Save Options'))

cms/apps/dashboard/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.http import Http404, HttpResponse
from django.shortcuts import render
from rolepermissions.checkers import has_permission, has_role
from rolepermissions.roles import assign_role, clear_roles, get_user_roles

from apps.accounts import roles as r
from apps.accounts.models import User
from apps.accounts.roles import Admin, Subscriber
from apps.core.constants import database_keys as dk
from apps.core.constants import permissions as p
from apps.core.utils import getOptions, setOption, getOption

from .forms import OptionsForm, PasswordChangeForm, RolesForm, UserForm
from .utils import getTableDataForUsers


@login_required
def IndexView(request):
    if has_role(request.user, Admin):
        context = {
            "count": {
                "users": User.objects.all().count()
            }
        }
        return render(request, "dashboard/index.html", {"data": context})
    elif has_role(request.user, Subscriber):
        return render(request, "dashboard/index-subscriber.html")
    else:
        raise PermissionDenied("You are not allowed to access this page!")


def BrowseUsersView(request):
    if has_permission(request.user, p.READ_USERS):
        enabled_columns = None
        sort_by = None
        sort_order = None
        search = None
        if request.GET.get('enabled_columns', False):
            enabled_columns = request.GET.getlist('enabled_columns')
        if request.GET.get('sort_by', False):
            sort_by = request.GET.get('sort_by')
        if request.GET.get('sort_order', False):
            sort_order = request.GET.get('sort_order')
        if request.GET.get('search', False):
            search = request.GET.get('search')

        tableData = getTableDataForUsers(enabled_columns=enabled_columns,
                                         search=search,
                                         sort_by=sort_by,
                                         sort_order=sort_order
                                         )
        return render(request, "dashboard/list.html", {"tableData": tableData})
    else:
        raise PermissionDenied("You are not allowed to List Users.")


@login_required
def UserEditView(request, userid=None):

    form = None
    user = None
    passForm = None
    rolesForm = None

    if userid == None:
        user = request.user
    elif has_permission(request.user, p.EDIT_USERS) or request.user.id == userid:
        try:
            user = User.objects.get(id=userid)
        except ObjectDoesNotExist as e:
            raise Http404("User Does Not Exist")
    else:
        raise PermissionDenied(
            "You do not have permission to edit/view this user")

    if has_permission(request.user, p.EDIT_USERS):
        roles = []
        for x in get_user_roles(user):
            roles.append(x.display_name)
        rolesForm = RolesForm({'roles': roles})

    form = UserForm(user=request.user, instance=user)
    passForm = PasswordChangeForm(user)

    if request.method == "POST":
        if 'user-submit' in request.POST:
            form = UserForm(user=request.user, data=request.POST or None,
                            files=request.FILES or None, instance=user)
            if form.is_valid():
                form.save()

        if 'password-change' in request.POST:
            passForm = PasswordChangeForm(user, request.POST or None)
            if passForm.is_valid():
                passForm.save()
                update_session_auth_hash(request, user)

        if 'change-role' in request.POST:
            rolesForm = RolesForm(request.POST or None)
            if rolesForm.is_valid():
                User().change_user_role(user, rolesForm.cleaned_data['roles'])

    return render(request, "dashboard/edit-user.html", {'form': form, 'user_context': user, 'passform': passForm, 'rolesForm': rolesForm})


@login_required
def ManageSiteView(request):
    if has_role(request.user, Admin):
        form = None
        if request.method == "POST":
            form = OptionsForm(data = request.POST, files = request.FILES or None)
            if form.is_valid():
                for data in form.cleaned_data:
                    setOption(data, form.cleaned_data[data])
        else:
            form = OptionsForm(initial=getOptions())
        return render(request, "dashboard/settings.html", {"form": form})
    else:
        raise PermissionDenied(
            "You do not have permissions to access this page!")

@login_required
def TestView(request):

    from apps.core.utils import send_mail

    return HttpResponse(send_mail("Test Mail", ["thisisayushaa@gmail.com"], "Test Mail Success!"))

cms/apps/dashboard/templates/dashboard/components/_footer.html
<footer class="footer">
  <div class="container">
    <div class="row align-items-center flex-row-reverse">
      <div class="col-auto ml-lg-auto">
        <div class="row align-items-center">
          <div class="col-auto">
            <a href="mailto:{{ meta.support_email|default:"support@theletstream.com" }}" class="btn btn-outline-primary btn-sm">Contact Support</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
        Copyright © 2018
        <a href=".">{{ meta.site_title|default:"Letstream" }}</a>. All rights reserved.
      </div>
    </div>
  </div>
</footer>

cms/apps/dashboard/templates/dashboard/components/_header.html
{% load static %}
<div class="header py-4">
    <div class="container">
        <div class="d-flex">
            <a class="header-brand" href="{% url 'dashboard:home' %}">
                <img src="{% static 'assets/images/clubpress-logo-black-full.png' %}" class="header-brand-img" alt="logo">
            </a>
            <div class="d-flex order-lg-2 ml-auto">
                <div class="nav-item d-none d-md-flex">
                    <a href="mailto:{{ meta.support_email }}" class="btn btn-sm btn-outline-primary">Contact Support</a>
                </div>
                <div class="dropdown">
                    <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
                        <span class="avatar" style="background-image: url('{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'assets/images/avatar.png' %}{% endif %}')"></span>
                        <span class="ml-2 d-none d-lg-block">
                            <span class="text-default">{{ user.get_full_name|default:'Howdy!' }}</span>
                            <small class="text-muted d-block mt-1">
                                {% if user_roles %}
                                    {% for role in user_roles %}{{ role|capfirst }}{% if not forloop.last %},{% endif %} {% endfor %} 
                                {% else %}
                                    Visitor
                                {% endif %}
                            </small>
                        </span>
                    </a>
                    {% if user.is_authenticated %}
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                        <a class="dropdown-item" href="{% url 'dashboard:profile' %}">
                            <i class="dropdown-icon fe fe-user"></i> Profile
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="mailto:support@afterbooks.in">
                            <i class="dropdown-icon fe fe-help-circle"></i> Need help?
                        </a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                            <i class="dropdown-icon fe fe-log-out"></i> Sign out
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
            <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                <span class="header-toggler-icon"></span>
            </a>
        </div>
    </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg order-lg-first">
                <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'dashboard:home' %}" class="nav-link">
                                <i class="fe fe-home"></i> Home
                            </a>
                        </li>
                        {% if user_roles %}
                            {% if "admin" in user_roles|lower %}
                            <li class="nav-item">
                                <a href="{% url 'dashboard:list-users' %}" class="nav-link">
                                    <i class="fe fe-user"></i> Users
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'dashboard:site-management' %}" class="nav-link">
                                    <i class="fe fe-settings"></i> Settings
                                </a>
                            </li>
                            {% endif %} 
                        {% endif %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>